# Brewfile
# Tap
tap "homebrew/cask-fonts"

# Brew
brew "antibody"
brew "sreenfetch"
brew "neovim"
brew "youtube-dl"
brew "aria2"
brew "nnn"
brew "ranger"
brew "ncdu"
brew "htop"
brew "python3"
brew "tmux"
brew "jrnl"

# Cask
# Internet
cask "firefox"
cask "google-chrome"
cask "tor-browser"
cask "authy"
cask "cyberduck"
cask "viber"
cask "netnewswire"
cask "transmission"
#Tool
cask "alfred"
cask "mounty"
cask "keka"
cask "appcleaner"
cask "iterm2"
cask "marta"
cask "zotero"
cask "itsycal"
cask "latest"
cask "java"
cask "mpv"
cask "knockknock"

#Media
cask "iina"
cask "vlc"
cask "gimp"
cask "handbrake"


#Bảo mật
cask "veracrypt"
cask "cryptomator"
# Tiếng việt
cask "openkey"

# Editor
cask "visual-studio-code"
cask "typora"

# Fonts
cask "font-hack-nerd-font"

# Latex
cask "mactex"
cask "texmaker"
cask "lyx"

# R Statictis
brew "r"
cask "rstudio"
